server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: zhfltm#12
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        transaction:
          jta:
            platform:
              org.hibernate.service.jta.JtaPlatform
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace

jwt:
  secret: oQf3q0QdluRt7fjejo4YNoxjbhFoclfC95mvFl66zCvzBkumTf